#!/bin/bash

# ==========================================================
# Weekly Unraid Backup Report Generator
# Version: v1.1.0
#
# Called by weekly_unraid_backup_v1.2.3.sh after a successful
# backup while the destination server is still online.
# Generates both a text report and a simple Paperless-ready PDF.
# ==========================================================

set -o pipefail

REPORT_SCRIPT_VERSION="v1.1.0"

META_FILE="${1:-}"
RUN_WORK_DIR="${2:-}"
REPORT_FILE="${3:-}"
PDF_REPORT_FILE="${4:-}"

if [ -z "$META_FILE" ] || [ -z "$RUN_WORK_DIR" ] || [ -z "$REPORT_FILE" ] || [ -z "$PDF_REPORT_FILE" ]; then
    echo "Usage: $0 META_FILE RUN_WORK_DIR REPORT_FILE PDF_REPORT_FILE"
    exit 1
fi

if [ ! -f "$META_FILE" ]; then
    echo "ERROR: Metadata file not found: $META_FILE"
    exit 1
fi

# This metadata file is generated by the paired backup script.
# shellcheck disable=SC1090
source "$META_FILE"

SHARES_PROCESSED_FILE="$RUN_WORK_DIR/shares_processed.txt"
CHANGES_DIR="$RUN_WORK_DIR/changes"
SHARE_TABLE_FILE="$RUN_WORK_DIR/share_report.tsv"

mkdir -p "$(dirname "$REPORT_FILE")"
: > "$SHARE_TABLE_FILE"

SSH_OPTS=(
    -i "$SSH_KEY"
    -o "UserKnownHostsFile=$KNOWN_HOSTS_FILE"
    -o StrictHostKeyChecking=yes
    -o UpdateHostKeys=no
    -o BatchMode=yes
)

human_bytes() {
    local BYTES="${1:-0}"

    if [ "$BYTES" = "SKIPPED" ]; then
        echo "not calculated"
        return 0
    fi

    if command -v numfmt >/dev/null 2>&1; then
        numfmt --to=iec-i --suffix=B "$BYTES" 2>/dev/null || echo "${BYTES} bytes"
        return 0
    fi

    awk -v bytes="$BYTES" '
        BEGIN {
            split("B KiB MiB GiB TiB PiB", unit, " ")
            i=1
            while (bytes >= 1024 && i < 6) {
                bytes = bytes / 1024
                i++
            }
            printf "%.2f %s\n", bytes, unit[i]
        }
    '
}

format_duration() {
    local SECONDS="${1:-0}"
    printf '%02d:%02d:%02d' \
        $((SECONDS / 3600)) \
        $(((SECONDS % 3600) / 60)) \
        $((SECONDS % 60))
}

parse_change_file() {
    local FILE="$1"

    awk -F'|' '
        $1 == "CHANGE" {
            code = $3
            bytes = $4 + 0

            # Sent regular file: newly created or updated on destination.
            if (substr(code, 1, 2) == ">f") {
                transferred_files++
                transferred_bytes += bytes
                if (code == ">f+++++++++") {
                    created_files++
                } else {
                    updated_files++
                }
            }

            # New directories are reported as cd+++++++++ by rsync.
            if (code == "cd+++++++++") {
                created_dirs++
            }

            # Symlinks and special items are counted separately.
            if (substr(code, 1, 2) == "cL" || substr(code, 1, 2) == ">L") {
                changed_links++
            }
        }
        END {
            printf "%d\t%d\t%d\t%d\t%d\t%.0f\n", \
                transferred_files + 0, created_files + 0, updated_files + 0, \
                created_dirs + 0, changed_links + 0, transferred_bytes + 0
        }
    ' "$FILE"
}

share_display_name() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "flash-config (/boot/config)"
    else
        echo "$SHARE"
    fi
}

local_share_path() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "/boot/config"
    else
        echo "/mnt/user/$SHARE"
    fi
}

remote_share_path() {
    local SHARE="$1"
    if [ "$SHARE" = "_flash_config" ]; then
        echo "/mnt/user/flash-backup-main-server"
    else
        echo "/mnt/user/$SHARE"
    fi
}

get_local_share_size() {
    local SHARE="$1"
    local PATH_TO_SCAN
    PATH_TO_SCAN="$(local_share_path "$SHARE")"
    du -sb -- "$PATH_TO_SCAN" 2>/dev/null | awk 'NR==1 {print $1}'
}

get_remote_share_size() {
    local SHARE="$1"
    local PATH_TO_SCAN QUOTED_PATH
    PATH_TO_SCAN="$(remote_share_path "$SHARE")"
    printf -v QUOTED_PATH '%q' "$PATH_TO_SCAN"

    ssh "${SSH_OPTS[@]}" root@"$DEST_IP" \
        "du -sb -- $QUOTED_PATH 2>/dev/null | awk 'NR==1 {print \$1}'" 2>/dev/null
}

SOURCE_DF="$(df -B1 /mnt/user 2>/dev/null | awk 'NR==2 {print $2"\t"$3"\t"$4}')"
DEST_DF="$(ssh "${SSH_OPTS[@]}" root@"$DEST_IP" "df -B1 /mnt/user 2>/dev/null | awk 'NR==2 {print \$2\"\\t\"\$3\"\\t\"\$4}'" 2>/dev/null)"

TOTAL_FILES=0
TOTAL_CREATED_FILES=0
TOTAL_UPDATED_FILES=0
TOTAL_CREATED_DIRS=0
TOTAL_CHANGED_LINKS=0
TOTAL_TRANSFER_BYTES=0
TOTAL_SOURCE_BYTES=0
TOTAL_DEST_BYTES=0

if [ ! -f "$SHARES_PROCESSED_FILE" ]; then
    echo "ERROR: Shares processed file not found: $SHARES_PROCESSED_FILE"
    exit 1
fi

while IFS= read -r SHARE; do
    [ -z "$SHARE" ] && continue

    CHANGE_FILE="$CHANGES_DIR/${SHARE}.changes"
    FILES=0
    CREATED_FILES=0
    UPDATED_FILES=0
    CREATED_DIRS=0
    CHANGED_LINKS=0
    TRANSFER_BYTES=0

    if [ -f "$CHANGE_FILE" ]; then
        IFS=$'\t' read -r FILES CREATED_FILES UPDATED_FILES CREATED_DIRS CHANGED_LINKS TRANSFER_BYTES \
            < <(parse_change_file "$CHANGE_FILE")
    fi

    if [ "${CALCULATE_SHARE_SIZES:-yes}" = "yes" ]; then
        SOURCE_BYTES="$(get_local_share_size "$SHARE")"
        DEST_BYTES="$(get_remote_share_size "$SHARE")"
        SOURCE_BYTES="${SOURCE_BYTES:-0}"
        DEST_BYTES="${DEST_BYTES:-0}"
        TOTAL_SOURCE_BYTES=$((TOTAL_SOURCE_BYTES + SOURCE_BYTES))
        TOTAL_DEST_BYTES=$((TOTAL_DEST_BYTES + DEST_BYTES))
    else
        SOURCE_BYTES="SKIPPED"
        DEST_BYTES="SKIPPED"
    fi

    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$SHARE" "$FILES" "$CREATED_FILES" "$UPDATED_FILES" "$CREATED_DIRS" \
        "$CHANGED_LINKS" "$TRANSFER_BYTES" "$SOURCE_BYTES" "$DEST_BYTES" >> "$SHARE_TABLE_FILE"

    TOTAL_FILES=$((TOTAL_FILES + FILES))
    TOTAL_CREATED_FILES=$((TOTAL_CREATED_FILES + CREATED_FILES))
    TOTAL_UPDATED_FILES=$((TOTAL_UPDATED_FILES + UPDATED_FILES))
    TOTAL_CREATED_DIRS=$((TOTAL_CREATED_DIRS + CREATED_DIRS))
    TOTAL_CHANGED_LINKS=$((TOTAL_CHANGED_LINKS + CHANGED_LINKS))
    TOTAL_TRANSFER_BYTES=$((TOTAL_TRANSFER_BYTES + TRANSFER_BYTES))
done < <(sort -u "$SHARES_PROCESSED_FILE")

DURATION_SECONDS=$((END_EPOCH - START_EPOCH))


# ----------------------------------------------------------
# Plain-text to PDF conversion without external dependencies.
# Uses core Bash utilities so it runs directly on Unraid.
# The PDF is intentionally monospaced for report-table readability.
# ----------------------------------------------------------
txt_to_pdf() {
    local INPUT_TEXT="$1"
    local OUTPUT_PDF="$2"
    local PDF_WORK_DIR WRAPPED_TEXT PDF_TEMP
    local LINES_PER_PAGE=66
    local PAGE_WIDTH_CHARS=108
    local PAGE_COUNT FONT_OBJECT OBJECT_COUNT
    local PAGE INDEX START_LINE END_LINE PAGE_OBJECT CONTENT_OBJECT
    local LINE ESCAPED CONTENT_FILE OBJECT_FILE PDF_OFFSET XREF_OFFSET
    local -a REPORT_LINES
    local -a OFFSETS

    if [ ! -s "$INPUT_TEXT" ]; then
        echo "ERROR: Cannot create PDF; text report is missing or empty: $INPUT_TEXT"
        return 1
    fi

    mkdir -p "$(dirname "$OUTPUT_PDF")" || return 1

    PDF_WORK_DIR="$(mktemp -d /tmp/weekly_unraid_pdf.XXXXXX)" || return 1
    WRAPPED_TEXT="$PDF_WORK_DIR/report_wrapped.txt"
    PDF_TEMP="$PDF_WORK_DIR/report.pdf"

    # Generated reports are ASCII. Strip unsupported control/high-byte characters,
    # retain tabs/newlines, and wrap long lines to fit a Letter-sized PDF page.
    LC_ALL=C tr -cd '\11\12\15\40-\176' < "$INPUT_TEXT" | \
        sed 's/\r$//' | \
        fold -s -w "$PAGE_WIDTH_CHARS" > "$WRAPPED_TEXT"

    mapfile -t REPORT_LINES < "$WRAPPED_TEXT"
    if [ "${#REPORT_LINES[@]}" -eq 0 ]; then
        REPORT_LINES=("")
    fi

    PAGE_COUNT=$(( (${#REPORT_LINES[@]} + LINES_PER_PAGE - 1) / LINES_PER_PAGE ))
    FONT_OBJECT=$((3 + (PAGE_COUNT * 2)))
    OBJECT_COUNT="$FONT_OBJECT"

    # Catalog.
    printf '<< /Type /Catalog /Pages 2 0 R >>\n' > "$PDF_WORK_DIR/obj_1"

    # Pages tree.
    {
        printf '<< /Type /Pages /Kids ['
        for ((PAGE=0; PAGE<PAGE_COUNT; PAGE++)); do
            PAGE_OBJECT=$((3 + (PAGE * 2)))
            printf '%s 0 R ' "$PAGE_OBJECT"
        done
        printf '] /Count %s >>\n' "$PAGE_COUNT"
    } > "$PDF_WORK_DIR/obj_2"

    # Page and content stream objects.
    for ((PAGE=0; PAGE<PAGE_COUNT; PAGE++)); do
        PAGE_OBJECT=$((3 + (PAGE * 2)))
        CONTENT_OBJECT=$((PAGE_OBJECT + 1))
        CONTENT_FILE="$PDF_WORK_DIR/content_${PAGE}.txt"
        START_LINE=$((PAGE * LINES_PER_PAGE))
        END_LINE=$((START_LINE + LINES_PER_PAGE))

        printf '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 %s 0 R >> >> /Contents %s 0 R >>\n' \
            "$FONT_OBJECT" "$CONTENT_OBJECT" > "$PDF_WORK_DIR/obj_${PAGE_OBJECT}"

        {
            printf 'BT\n/F1 8 Tf\n10 TL\n36 756 Td\n'
            for ((INDEX=START_LINE; INDEX<END_LINE && INDEX<${#REPORT_LINES[@]}; INDEX++)); do
                LINE="${REPORT_LINES[$INDEX]}"
                ESCAPED="${LINE//\\/\\\\}"
                ESCAPED="${ESCAPED//\(/\\(}"
                ESCAPED="${ESCAPED//\)/\\)}"
                printf '(%s) Tj\nT*\n' "$ESCAPED"
            done
            printf 'ET\n'
        } > "$CONTENT_FILE"

        {
            printf '<< /Length %s >>\nstream\n' "$(wc -c < "$CONTENT_FILE" | tr -d ' ')"
            cat "$CONTENT_FILE"
            printf 'endstream\n'
        } > "$PDF_WORK_DIR/obj_${CONTENT_OBJECT}"
    done

    # Courier base font requires no embedded font file.
    printf '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\n' > "$PDF_WORK_DIR/obj_${FONT_OBJECT}"

    # Assemble PDF and track byte offsets for xref table.
    printf '%%PDF-1.4\n%%\342\343\317\323\n' > "$PDF_TEMP"
    OFFSETS[0]=0

    for ((INDEX=1; INDEX<=OBJECT_COUNT; INDEX++)); do
        PDF_OFFSET="$(wc -c < "$PDF_TEMP" | tr -d ' ')"
        OFFSETS[$INDEX]="$PDF_OFFSET"
        {
            printf '%s 0 obj\n' "$INDEX"
            cat "$PDF_WORK_DIR/obj_${INDEX}"
            printf 'endobj\n'
        } >> "$PDF_TEMP"
    done

    XREF_OFFSET="$(wc -c < "$PDF_TEMP" | tr -d ' ')"
    {
        printf 'xref\n0 %s\n' "$((OBJECT_COUNT + 1))"
        printf '0000000000 65535 f \n'
        for ((INDEX=1; INDEX<=OBJECT_COUNT; INDEX++)); do
            printf '%010d 00000 n \n' "${OFFSETS[$INDEX]}"
        done
        printf 'trailer\n<< /Size %s /Root 1 0 R >>\n' "$((OBJECT_COUNT + 1))"
        printf 'startxref\n%s\n%%%%EOF\n' "$XREF_OFFSET"
    } >> "$PDF_TEMP"

    if mv -f "$PDF_TEMP" "$OUTPUT_PDF"; then
        rm -rf "$PDF_WORK_DIR"
        return 0
    fi

    rm -rf "$PDF_WORK_DIR"
    return 1
}

{
    echo "======================================================================"
    echo "Weekly Unraid Backup Report"
    echo "======================================================================"
    echo "Run ID:                  $RUN_ID"
    echo "Backup script version:   $SCRIPT_VERSION"
    echo "Report script version:   $REPORT_SCRIPT_VERSION"
    echo "Mode:                    $MODE"
    echo "Status:                  SUCCESS"
    echo "Started:                 $START_TIME"
    echo "Finished:                $END_TIME"
    echo "Duration:                $(format_duration "$DURATION_SECONDS")"
    echo
    echo "Servers"
    echo "----------------------------------------------------------------------"
    echo "Main/source:             $SOURCE_IP"
    echo "Backup/destination:      $DEST_IP"
    echo
    echo "Backup policy"
    echo "----------------------------------------------------------------------"
    echo "Delete from backup:      NO"
    echo "Excluded share:          CCTVStorage"
    echo "Excluded report share:   BackupReports"
    echo "Excluded system images:  docker/docker.img, libvirt/libvirt.img"
    echo "Appdata excludes:        Cache/cache/tmp/temp/logs/*.sock/*.pid"
    echo "Credential excluded:     appdata/ipmi_tools/backup_bmc.pass"
    echo
    echo "Transfer totals for this run"
    echo "----------------------------------------------------------------------"
    printf 'Files transferred:       %d\n' "$TOTAL_FILES"
    printf 'New files created:       %d\n' "$TOTAL_CREATED_FILES"
    printf 'Existing files updated:  %d\n' "$TOTAL_UPDATED_FILES"
    printf 'Folders created:         %d\n' "$TOTAL_CREATED_DIRS"
    printf 'Links changed:           %d\n' "$TOTAL_CHANGED_LINKS"
    echo "Data transferred:        $(human_bytes "$TOTAL_TRANSFER_BYTES")"
    echo
    echo "Per-share transfer summary"
    echo "----------------------------------------------------------------------"
    printf '%-30s %10s %10s %10s %12s %15s\n' "Share" "Files" "New" "Updated" "Folders" "Transferred"
    printf '%-30s %10s %10s %10s %12s %15s\n' "------------------------------" "----------" "----------" "----------" "------------" "---------------"

    while IFS=$'\t' read -r SHARE FILES CREATED UPDATED DIRS LINKS BYTES SOURCE_BYTES DEST_BYTES; do
        printf '%-30s %10s %10s %10s %12s %15s\n' \
            "$(share_display_name "$SHARE")" "$FILES" "$CREATED" "$UPDATED" "$DIRS" "$(human_bytes "$BYTES")"
    done < "$SHARE_TABLE_FILE"

    echo
    echo "Current storage footprint after backup"
    echo "----------------------------------------------------------------------"
    echo "Destination sizes can be larger because no-delete retains files that"
    echo "are no longer present on the main server. Size scans may add runtime."
    echo

    if [ "${CALCULATE_SHARE_SIZES:-yes}" = "yes" ]; then
        printf '%-30s %18s %18s\n' "Share" "Main size" "Backup size"
        printf '%-30s %18s %18s\n' "------------------------------" "------------------" "------------------"

        while IFS=$'\t' read -r SHARE FILES CREATED UPDATED DIRS LINKS BYTES SOURCE_BYTES DEST_BYTES; do
            printf '%-30s %18s %18s\n' \
                "$(share_display_name "$SHARE")" "$(human_bytes "$SOURCE_BYTES")" "$(human_bytes "$DEST_BYTES")"
        done < "$SHARE_TABLE_FILE"

        echo
        printf '%-30s %18s %18s\n' "TOTAL PROCESSED PATHS" \
            "$(human_bytes "$TOTAL_SOURCE_BYTES")" "$(human_bytes "$TOTAL_DEST_BYTES")"
    else
        echo "Per-share size scan disabled in backup script configuration."
    fi

    echo
    echo "Filesystem capacity"
    echo "----------------------------------------------------------------------"

    if [ -n "$SOURCE_DF" ]; then
        IFS=$'\t' read -r FS_TOTAL FS_USED FS_FREE <<< "$SOURCE_DF"
        echo "Main /mnt/user total:    $(human_bytes "$FS_TOTAL")"
        echo "Main /mnt/user used:     $(human_bytes "$FS_USED")"
        echo "Main /mnt/user free:     $(human_bytes "$FS_FREE")"
    else
        echo "Main /mnt/user capacity: unavailable"
    fi

    if [ -n "$DEST_DF" ]; then
        IFS=$'\t' read -r FS_TOTAL FS_USED FS_FREE <<< "$DEST_DF"
        echo "Backup /mnt/user total:  $(human_bytes "$FS_TOTAL")"
        echo "Backup /mnt/user used:   $(human_bytes "$FS_USED")"
        echo "Backup /mnt/user free:   $(human_bytes "$FS_FREE")"
    else
        echo "Backup /mnt/user capacity: unavailable"
    fi

    echo
    echo "Notes"
    echo "----------------------------------------------------------------------"
    echo "- Files present only on the backup server are retained."
    echo "- Existing destination files are overwritten when the main copy changes."
    echo "- Transfer totals describe this run only; footprint describes current data."
    echo "======================================================================"
} | tee "$REPORT_FILE"

echo "Creating PDF report: $PDF_REPORT_FILE"
if ! txt_to_pdf "$REPORT_FILE" "$PDF_REPORT_FILE"; then
    echo "ERROR: Failed to create PDF report: $PDF_REPORT_FILE"
    exit 1
fi

echo "PDF report created: $PDF_REPORT_FILE"

exit 0
